export default class TickTask {
  constructor(options) {
    this.id = null
    this.projectId = null
    this.sortOrder = null
    this.title = null
    this.content = null
    this.desc = null
    this.startDate = null
    this.dueDate = null
    this.timeZone = null
    this.isAllDay = null
    this.reminder = null
    this.reminders = null
    this.repeatFirstDate = null
    this.repeatFlag = null
    this.completedTime = null
    this.completedUserId = null
    this.repeatTaskId = null
    this.priority = null
    this.status = null
    this.items = null
    this.progress = null
    this.modifiedTime = null
    this.etag = null
    this.deleted = null
    this.createdTime = null
    this.creator = null
    this.remindTime = null
    this.location = null
    this.repeatFrom = null
    this.tags = null
    this.attachments = null
    this.commentCount = null
    this.assignee = null
    this.pomodoroSummaries = null
    this.userId = null
    this.kind = null
    if (options.id) this.id = options.id
    if (options.projectId) this.projectId = options.projectId
    if (options.sortOrder) this.sortOrder = options.sortOrder
    if (options.title) this.title = options.title
    if (options.content) this.content = options.content
    if (options.desc) this.desc = options.desc
    if (options.startDate) this.startDate = options.startDate
    if (options.dueDate) this.dueDate = options.dueDate
    if (options.timeZone) this.timeZone = options.timeZone
    if (options.isAllDay) this.isAllDay = options.isAllDay
    if (options.reminder) this.reminder = options.reminder
    if (options.reminders) this.reminders = options.reminders
    if (options.repeatFirstDate) this.repeatFirstDate = options.repeatFirstDate
    if (options.repeatFlag) this.repeatFlag = options.repeatFlag
    if (options.completedTime) this.completedTime = options.completedTime
    if (options.completedUserId) this.completedUserId = options.completedUserId
    if (options.repeatTaskId) this.repeatTaskId = options.repeatTaskId
    if (options.priority) this.priority = options.priority
    if (options.status) this.status = options.status
    if (options.items) this.items = options.items
    if (options.progress) this.progress = options.progress
    if (options.modifiedTime) this.modifiedTime = options.modifiedTime
    if (options.etag) this.etag = options.etag
    if (options.deleted) this.deleted = options.deleted
    if (options.createdTime) this.createdTime = options.createdTime
    if (options.creator) this.creator = options.creator
    if (options.remindTime) this.remindTime = options.remindTime
    if (options.location) this.location = options.location
    if (options.repeatFrom) this.repeatFrom = options.repeatFrom
    if (options.tags) this.tags = options.tags
    if (options.attachments) this.attachments = options.attachments
    if (options.commentCount) this.commentCount = options.commentCount
    if (options.assignee) this.assignee = options.assignee
    if (options.pomodoroSummaries) this.pomodoroSummaries = options.pomodoroSummaries
    if (options.userId) this.userId = options.userId
    if (options.kind) this.kind = options.kind
  }
}
